[package]
name = "stm32-monotonic"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
hal = { package = "stm32f4xx-hal", version = "0.23.0", features = [
    "stm32f401",
  #  "defmt",
] }
